### ISSUE TITLE
`"transparent"` and `NA_character_` are not valid color names

### ISSUE THREAD

**Issue by trevorld** [coolbutuseless/colourlookup#1]
```r
library("colourlookup")
col_to_rgb("transparent")
```
```
Error in col_to_packed_int("transparent") : 
  Not a valid colour name: transparent
```
```r
col_to_rgb(NA_character_)
```
```
Error in col_to_rgb(NA_character_) : Not a valid colour name: NA
```

**Comment by coolbutuseless** [comment]
Have a try now.

This technique will probably get ported into `{nara}` so I appreciate the report!

**Comment by trevorld** [comment]
Looks good now!  Note sometimes people are lazy and expect a logical `NA` to act the same as the more verbose `NA_character_`:

```r
col_to_rgb(col=NA)
```
```
Error in col_to_rgb(col = NA) : 
  STRING_ELT() can only be applied to a 'character vector', not a 'logical'
```

Compare with `grDevices::col2rgb()`:

```r
> col2rgb(NA)
      [,1]
red    255
green  255
blue   255
> col2rgb(TRUE)
Error in col2rgb(TRUE) : invalid color name 'TRUE'
> col2rgb(FALSE)
Error in col2rgb(FALSE) : invalid color name 'FALSE'
```

**Comment by coolbutuseless** [comment]
I've fixed it such:

* logical NAs are treated as 'transparent'
* A vector of logical NAs are treated as a vector of 'transparent'
* A vector of logicals with non-NA values will throw an error.

Any more corner cases up your sleeve? :)

**Comment by trevorld** [comment]
> Any more corner cases up your sleeve?

I don't know who uses this but to be a true "drop-in replacement to `col2rgb()`" there are also the "positive numeric" values as a shortcut to `palette()[x]` e.g.

```r
> col2rgb(3L)
      [,1]
red     97
green  208
blue    79
> col2rgb(palette()[3L])
      [,1]
red     97
green  208
blue    79
> col2rgb(3.999)
      [,1]
red     97
green  208
blue    79
> col2rgb(3.999999999999999999)
      [,1]
red     34
green  151
blue   230

```

**Comment by coolbutuseless** [comment]
I'm happy to leave that case in the corner!
